### ISSUE TITLE
Version 0.5.1 release on Github not shown on PyPI

### ISSUE THREAD

**Issue by hsheth2** [googleapis/python-bigquery-sqlalchemy#113] opened 2021-04-06 02:21 UTC
There's a new release on Github: https://github.com/googleapis/python-bigquery-sqlalchemy/releases/tag/v0.5.1, but I don't see a corresponding release on PyPI: https://pypi.org/project/pybigquery/#history. Seems like the release automation failed https://github.com/googleapis/python-bigquery-sqlalchemy/pull/92?

**Comment by tswast** [comment] 2021-04-06 15:44
Thanks for the report! I also noticed this. The root cause is that I missed a comma in `setup.py`. Should be fixed by https://github.com/googleapis/python-bigquery-sqlalchemy/pull/107, going out as `0.6.0` in https://github.com/googleapis/python-bigquery-sqlalchemy/pull/116

**Comment by tswast** [comment] 2021-04-06 15:53
https://pypi.org/project/pybigquery/0.6.0/ is now published.

**Closed by tswast** 2021-04-06 15:53 UTC
Labels: api: bigquery, priority: p1, type: bug

**Comment by hsheth2** [comment] 2021-04-07 01:16
Thanks @tswast!
