### ISSUE TITLE
Use of refresh token to connect.

### ISSUE THREAD

**Issue by jaythacker** [googleapis/python-bigquery-sqlalchemy#223] opened 2021-07-21 06:58 UTC
is there any way to provide refresh token and connect with that? I want to provide refresh token from superset to impersonate users.

**Comment by tswast** [comment] 2021-08-03 18:11
This is a great feature request. I imagine this is an additional parameter to the connection string URL parsing that we'd need to add.

There's some discussion here: https://github.com/googleapis/python-bigquery-sqlalchemy/issues/42

I'll close this issue as a duplicate of that.

**Closed by tswast** 2021-08-03 18:11 UTC
Labels: api: bigquery, type: feature request
