### ISSUE TITLE
Percentage symbols get duplicated when compile to SQL string

### ISSUE THREAD

**Issue by woidda** [googleapis/python-bigquery-sqlalchemy#418] opened 2022-02-25 08:02 UTC
We are trying to create SQL queries as strings with LIKE operators. It seems that the percentage sign is added twice to the query.

**DISCLAIMER:** I am quite new to sqlalchemy, because until now I did not require it for my python needs. So I might not see some param to make it work with the biquery dialect as it is available for the PostgreSQL dialect [see](https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#why-are-percent-signs-being-doubled-up-when-stringifying-sql-statements). I apologize in advance if this issue does not make and I simply could not find the right config.  

The issue might be in [this line](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/main/sqlalchemy_bigquery/base.py#L666). Might be good to check if this is required.

#### Environment details

  - OS type and version: Ubuntu kernel 5.10.0-1052-oem
  - Python version: `Python 3.10.2`
  - pip version: `pip 21.1.2`
  - `sqlalchemy-bigquery` version: `Version: 1.4.0`

#### Steps to reproduce

  1. Run the test
  2. See it fails, because it adds an additional percentage sign:  it should be `LIKE '%somestring'` instead of  `LIKE '%%somestring'`

#### Code example

```python
import unittest

from sqlalchemy import column, select
from sqlalchemy.engine import create_mock_engine
from sqlalchemy.schema import Table, MetaData


def dump(sql, *multiparams, **params):
    sql.compile(dialect=engine.dialect(paramstyle="named"))


def sample_query():
    engine = create_mock_engine('bigquery://', dump)
    table = Table("sample_table", MetaData(bind=engine), autoload=False)
    query = (select("*", from_obj=table).where(column("some_column").like('%somestring')))
    return str(query.compile(None, compile_kwargs={"literal_binds": True}))


class PercentageTest(unittest.TestCase):

    def test_something(self):
        query = sample_query()
        expected = "SELECT * \nFROM `sample_table` \nWHERE `some_column` LIKE '%somestring'"
        self.assertEqual(expected, query)


if __name__ == '__main__':
    unittest.main()

```

#### Stack trace
```
# none available -> just a potential bug
```

**Comment by tswast** [comment] 2022-02-28 18:09
I believe the extra percent sign is needed so that the DB-API module can use the [pystyle paramformat](https://www.python.org/dev/peps/pep-0249/#paramstyle). Unfortunately the BigQuery-style params are not one of the standard DB-API types, so we have to do some string formatting before passing to the BigQuery API.

**Comment by tswast** [comment] 2022-02-28 22:27
I'm converting this to a Feature Request, as I believe it'd be great if we could generate BigQuery-acceptable SQL in addition to DB-API-acceptable SQL. Alternatively, we may possibly want to expose the text transformations the DB-API does, publicly.

**Comment by woidda** [comment] 2022-03-01 07:32
Thanks. 

Well, might indeed be a feature request, depending the scope of this library. If the scope is only to generate DB-API-acceptable SQL then this is indeed a new feature.  

For unit testing where I want to test against generated SQL I use a decorator with a `re.sub("%%", "%", value)` for now...

**Comment by chalmerlowe** [comment] 2024-04-18 13:50
I am not able to replicate this issue locally.
Closing.

**Comment by YonatanCatav** [comment] 2024-05-06 12:39
it happened to me now..
as described above..
@woidda 
if you have some tip how to workaround this issue let me know please :)

**Comment by chalmerlowe** [comment] 2024-05-08 14:35
@YonatanCatav @tswast 

I ran code pretty similar to what is listed above and got the following outputs:

#### EXPECTED
```
SELECT * 
FROM sample_table 
WHERE some_column LIKE '%somestring'
```

#### QUERY OUTPUT
```
SELECT * 
FROM sample_table 
WHERE some_column LIKE '%somestring'
```

#### Versions:
sqlalchemy-bigquery - 1.8.0
sqlalchemy - 1.4.52
os - Apple
pip - 23.3.2
Python - 3.10.12

**Comment by tswast** [comment] 2024-05-08 19:09
I'm able to reproduce with a public dataset and the following code sample:

```python
import sqlalchemy

sqlalchemy.__version__
# 2.0.30

import sqlalchemy_bigquery

sqlalchemy_bigquery.__version__
# 1.11.0

from google.colab import auth
auth.authenticate_user()

engine = sqlalchemy.create_engine("bigquery://swast-scratch")
connection = engine.connect()
metadata = sqlalchemy.MetaData()

table = sqlalchemy.Table(
    "bigquery-public-data.usa_names.usa_1910_2013",
    metadata,
    autoload_with=engine,
)
q = sqlalchemy.select(table).where(table.c.state.like("W%"))
print(str(q.compile(dialect=sqlalchemy_bigquery.dialect(), compile_kwargs={"literal_binds": True})))
# SELECT `bigquery-public-data.usa_names.usa_1910_2013`.`state`, `bigquery-public-data.usa_names.usa_1910_2013`.`gender`, `bigquery-public-data.usa_names.usa_1910_2013`.`year`, `bigquery-public-data.usa_names.usa_1910_2013`.`name`, `bigquery-public-data.usa_names.usa_1910_2013`.`number` 
# FROM `bigquery-public-data.usa_names.usa_1910_2013` 
# WHERE `bigquery-public-data.usa_names.usa_1910_2013`.`state` LIKE 'W%%'

connection.execute(q).fetchall()
# ...
# ('WA', 'F', 1996, 'Erika', 68),
# ('WA', 'F', 1996, 'Megan', 278),
# ('WA', 'F', 1996, 'Jennifer', 195),
# ...
```

As you can see, this executes fine. I am also able to execute it fine using the BigQuery DB-API library.

```python
import google.cloud.bigquery
import google.cloud.bigquery.dbapi as dbapi

q_str = str(q.compile(dialect=sqlalchemy_bigquery.dialect(), compile_kwargs={"literal_binds": True}))
bqclient = google.cloud.bigquery.Client(project="swast-scratch")
dbconn = dbapi.connect(bqclient)
dbcur = dbconn.cursor()
dbcur.execute(q_str)
dbcur.fetchall()
# ...
# Row(('WA', 'F', 1990, 'Melissa', 278), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4}),
# Row(('WA', 'F', 1990, 'Kristen', 96), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4}),
# Row(('WA', 'F', 1990, 'Ashley', 804), {'state': 0, 'gender': 1, 'year': 2, 'name': 3, 'number': 4})
# ...
```

I'm inclined to mark this issue as "working as intended". The intention of this package is _not_ to provide BigQuery SQL that can be executed in any environment but instead SQL that can be executed in a valid Python DB-API client.

You can file a feature request for a BigQuery-compatible paramstyle for the DB-API at https://github.com/googleapis/python-bigquery/issues but not that BigQuery-style named parameters with `@` are not one of the acceptable options listed at https://peps.python.org/pep-0249/#paramstyle

**Closed by tswast** 2024-05-08 19:09 UTC
Labels: type: feature request, status: will not fix, api: bigquery
