### ISSUE TITLE
Cannot install pybiquery for Python 3.10

### ISSUE THREAD

**Issue by munro** [googleapis/python-bigquery-sqlalchemy#417] opened 2022-02-24 18:12 UTC
When I try to add `pybigquery` to my Python 3.10 project, I'm getting an error about it not supporting Python 3.10 😢 

Even though I see support was added https://github.com/googleapis/python-bigquery-sqlalchemy/issues/374 !

```bash
poetry add pybigquery
```

```
Using version ^0.10.2 for pybigquery

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - pybigquery requires Python >=3.6, <3.10, so it will not be satisfied for Python >=3.10,<4.0
  
  Because pybigquery (0.10.2) requires Python >=3.6, <3.10
   and no versions of pybigquery match >0.10.2,<0.11.0, pybigquery is forbidden.
  So, because kw-kitchen-sink depends on pybigquery (^0.10.2), version solving failed.

  at /usr/local/Cellar/poetry/1.1.12/libexec/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pybigquery, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by tswast** [comment] 2022-02-28 22:28
I'm closing this as "working as intended", but please do let us know if you encounter issues migrating to `sqlalchemy-bigquery`.

**Closed by tswast** 2022-02-28 22:28 UTC
Labels: type: question, api: bigquery
